FROM python:3.10-slim-bullseye

# cria usuário não-root
RUN addgroup --system appgroup && adduser --system appuser --ingroup appgroup

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# troca para usuário seguro
USER appuser

EXPOSE 5000

CMD ["python", "-m", "app.api.app"]