sonar.projectKey=helpdesk-bot
sonar.projectName=MVRC-HelpdeskBot

sonar.sources=app
sonar.tests=tests

sonar.python.version=3

sonar.python.coverage.reportPaths=coverage.xml

# Ignorar duplicação em testes
sonar.cpd.exclusions=tests/**

# Ignorar arquivos irrelevantes no coverage
sonar.coverage.exclusions=tests/**,__pycache__/**,.pytest_cache/**,venv/**

# Encoding
sonar.sourceEncoding=UTF-8